name = "rwa-project-platform"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Pages configuration
pages_build_output_dir = "./static"

# D1 Database bindings
[[d1_databases]]
binding = "DB"
database_name = "rwa-database"
database_id = "bb36b797-31e6-481f-a299-87582530a68a"

# AI binding for Cloudflare Workers AI
[ai]
binding = "AI"

# R2 Storage binding for file uploads
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "rwa-project-files"
preview_bucket_name = "rwa-project-files-preview"

# KV namespace for caching
[[kv_namespaces]]
binding = "CACHE"
id = "884a1c8359d84d81b877e4edc1cc8d62"

# Environment variables
[vars]
ENVIRONMENT = "production"
API_BASE_URL = "https://rwa-project-platform.pages.dev"

# Note: build and routes configurations are handled by Cloudflare Pages automatically
# Functions are auto-detected from the functions/ directory
# Static files are served from pages_build_output_dir

# Security headers
[env.production.vars]
CSP_HEADER = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:;"